name: Stable Release
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  publish_stable:
    uses: TigreGotico/gh-automations/.github/workflows/publish-stable.yml@master
    with:
      branch: 'master'
      version_file: 'ovos_PHAL_plugin_mk1/version.py'
      setup_py: 'setup.py'
      publish_release: true
      publish_pypi: true
    permissions:
      id-token: write

  sync_dev:
    needs: publish_stable
    if: success()  # Ensure this job only runs if the previous job succeeds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          ref: master
      - name: Push master -> dev
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev